export const categoriesStoreSelf = [
  "Acolchadora",
  "Adaptador",
  "Antigüedades y arículos de colección",
  "Arte y manualidades",
  "Auriculares",
  "Autopartes",
  "Bebés y niños",
  "Bicicletas",
  "Boletas",
  "Bolígrafo",
  "Bolsos y equipajes",
  "Bolsos",
  "Cables",
  "Calculadora",
  "Cargador de móvil",
  "Cargador",
  "Carpeta de anillas",
  "Carpeta de archivo",
  "Carpetas",
  "Cartucheras",
  "Casa y jardin",
  "Celular",
  "Cinta adhesiva",
  "Clips",
  "Compás",
  "Corrector",
  "Cuaderno",
  "Deportes y actividades al aire libre",
  "Diccionario",
  "Disco duro externo",
  "Electrodomésticos",
  "Electrónica e informática",
  "Electrónica",
  "Entretenimiento",
  "Familia",
  "Folios",
  "Goma de borrar",
  "Gorras",
  "Grapadora",
  "Herramientas",
  "Hogar",
  "Instrumentos musicales",
  "Jardinería",
  "Joyas y accesorios",
  "Juguetes y juegos",
  "Lámparas",
  "Lapices",
  "Lápiz",
  "Laptop",
  "Libreta de notas",
  "Libretas",
  "Libros, películas y música",
  "Libros",
  "Marcadores",
  "Mochila",
  "Módem",
  "Muebles",
  "Otros",
  "Pantalón",
  "Papelería",
  "Pasatiempos",
  "Pilas",
  "Portaminas",
  "Post-it",
  "Productos para mascotas",
  "Pulseras",
  "Regla",
  "Resaltadores",
  "Ropa y accesorios",
  "Ropa y calzado de hombre",
  "Ropa y calzado de mujer",
  "Sacapuntas",
  "Salud y belleza",
  "Sueter",
  "Tableta",
  "Talonario",
  "Teléfono celulares",
  "Tijeras",
  "USB",
  "Videojuegos",
  "Zapatos",
];

export const state_product = [
  "Nuevo",
  "Usado - Como nuevo",
  "Usado - Buen estado",
  "Usado - Aceptable",
];
