// import {
//     read,
//     tv,
//     family,
//     cinema,
//     fish,
//     computer,
//     garden,
//     movie,
//     walk,
//     sports,
//     music,
//     shores,
//     buy,
//     travel,
//     sleep,
//     speaking,
//     hunt,
//     golf,
//     sew,
//   } from "../images/hobbies";

//   export const listHobbies = [
//     {
//       id: 1,
//       name: "Leer",
//       isSelected: false,
//       img: read,
//     },
//     {
//       id: 2,
//       name: "Ver la tele",
//       isSelected: false,
//       img: tv,
//     },
//     {
//       id: 3,
//       name: "Pasar tiempo con la familia",
//       isSelected: false,
//       img: family,
//     },
//     {
//       id: 4,
//       name: "Ir al cine",
//       isSelected: false,
//       img: cinema,
//     },
//     {
//       id: 5,
//       name: "Pescar",
//       isSelected: false,
//       img: fish,
//     },
//     {
//       id: 6,
//       name: "Pasar el tiempo en el PC o portátil",
//       isSelected: false,
//       img: computer,
//     },
//     {
//       id: 7,
//       name: "Dedicarse a la jardinería",
//       isSelected: false,
//       img: garden,
//     },

//     {
//       id: 8,
//       name: "Alquilar películas",
//       isSelected: false,
//       img: movie,
//     },

//     {
//       id: 9,
//       name: "Pasear",
//       isSelected: false,
//       img: walk,
//     },

//     {
//       id: 10,
//       name: "Hacer ejercicio",
//       isSelected: false,
//       img: sports,
//     },

//     {
//       id: 11,
//       name: "Escuchar música",
//       isSelected: false,
//       img: music,
//     },

//     {
//       id: 12,
//       name: "Realizar pequeñas tareas divertidas",
//       isSelected: false,
//       img: shores,
//     },

//     {
//       id: 13,
//       name: "Ir de caza",
//       isSelected: false,
//       img: hunt,
//     },

//     {
//       id: 14,
//       name: "Practicar deportes en equipo",
//       isSelected: false,
//       img: sports,
//     },

//     {
//       id: 15,
//       name: " Ir de compras",
//       isSelected: false,
//       img: buy,
//     },

//     {
//       id: 16,
//       name: "Viajar",
//       isSelected: false,
//       img: travel,
//     },

//     {
//       id: 17,
//       name: "Dormir",
//       isSelected: false,
//       img: sleep,
//     },

//     {
//       id: 18,
//       name: "Socializarse",
//       isSelected: false,
//       img: speaking,
//     },

//     {
//       id: 19,
//       name: "Coser",
//       isSelected: false,
//       img: sew,
//     },

//     {
//       id: 20,
//       name: " Jugar al golf",
//       isSelected: false,
//       img: golf,
//     },
//   ];

export const listJobs = [
  "En la vagancia",
  "No trabajo me mantienen",
  "Tengo suggar mommy",
  "Tengo suggar daddy",
  "Mi unico trabajo es existir",
  "Viviendo, pero a que costo?",
  "En only fans",
  "Ingeniero en sistemas",
  "Desarrollador de software",
  "Cantante",
  "Deportista",
  "Alcoholizarme",
  "Lechero",
  "Frutero",
  "Cerrajero",
  "Cocinero",
  "Deshollinador",
  "Mecánico",
  "Lavandero",
  "Artesano",
  "Pescador",
  "Escultor",
  "Tornero",
  "Albañil",
  "Editor",
  "Barrendero",
  "Fontanero o plomero",
  "Obrero",
  "Panadero",
  "Carpintero",
  "Locutor",
  "Barbero",
  "Soldador",
  "Escritor",
  "Leñador",
  "Pintor de brocha gorda",
  "Vendedor",
  "Peletero",
  "Sastre",
  "Repartidor",
  "Impresor",
  "Pastor",
  "ganadero",
  "Cajero",
  "Policía",
  "Agricultor",
  "Vigilante",
  "Exterminador",
  "Carnicero",
  "Animador",
  "Peluquero",
  "otro",
];

export const listRelationships = [
  "En una relación",
  "En una relación toxica",
  "Solter@",
  "Pareja quejeso?",
  "Solo solin solo",
  "En busca de alguien que me ame",
  "Esperando un milagro",
  "En 5 relaciones serias",
  "Lllevando cacho ando",
  "Soy programador bro, de que pareja hablas?",
  "Mejor me pongo a aprender ingles",
  "otro",
];
